#!/usr/bin/env /Users/l/.emacs.d/bin/doomscript
(provide 'tadwin)
(require 'doom-start)
(require 'json)
(load "~/blog/id.el")
(load "~/blog/formats.el")
(setq indent-bars-starting-column 99)

;; Hugo ID → URL mapping (read from JSON generated by Hugo build)
(defvar salih/hugo-id-mapping nil
  "Alist mapping Hugo content org IDs to their URLs.")

(defvar salih/hugo-sections nil
  "List of Hugo content sections derived from hugo_ids.json.")

(defun salih/load-hugo-id-mapping ()
  "Load Hugo ID mapping from JSON file generated after Hugo build."
  (let ((json-file "/Users/l/roam/hugo/oldblog/hugo_ids.json"))
    (if (file-exists-p json-file)
        (let ((json-object-type 'alist)
              (json-array-type 'list)
              (json-key-type 'string))
          (setq salih/hugo-id-mapping (json-read-file json-file))
          ;; Extract unique sections from URLs (e.g., "/microblog/2025-01-01/" -> "microblog")
          (setq salih/hugo-sections
                (delete-dups
                 (mapcar (lambda (pair)
                           (let ((url (cdr pair)))
                             (when (string-match "^/\\([^/]+\\)/" url)
                               (match-string 1 url))))
                         salih/hugo-id-mapping)))
          (message "Loaded Hugo ID mapping with %d entries, %d sections"
                   (length salih/hugo-id-mapping)
                   (length salih/hugo-sections)))
      (message "Warning: Hugo ID mapping file not found: %s" json-file)
      (setq salih/hugo-id-mapping nil)
      (setq salih/hugo-sections nil))))

;; Load mapping at startup
(salih/load-hugo-id-mapping)

;; Blog ID → URL mapping (read from JSON generated by blog export)
(defvar salih/blog-id-mapping nil
  "Alist mapping blog content org IDs to their URLs.")

(defun salih/load-blog-id-mapping ()
  "Load blog ID mapping from JSON file."
  (let ((json-file "/Users/l/roam/hugo/data/blog_ids.json"))
    (if (file-exists-p json-file)
        (let ((json-object-type 'alist)
              (json-array-type 'list)
              (json-key-type 'string))
          (setq salih/blog-id-mapping (json-read-file json-file))
          (message "Loaded blog ID mapping with %d entries"
                   (length salih/blog-id-mapping)))
      (message "Warning: Blog ID mapping file not found: %s" json-file)
      (setq salih/blog-id-mapping nil))))

;; Load blog mapping at startup
(salih/load-blog-id-mapping)

(defun salih/prefix-absolute-paths (output backend info)
  "Prefix absolute paths with /~saleh for the nested static site.
Excludes Hugo content URLs (sections derived from hugo_ids.json)."
  (if (org-export-derived-backend-p backend 'html)
      (let ((result output))
        (if salih/hugo-sections
            (let ((sections-pattern (regexp-opt salih/hugo-sections)))
              ;; First, mark Hugo URLs so they don't get prefixed
              (setq result (replace-regexp-in-string
                            (format "\\(href\\|src\\)=\"/\\(%s\\)/" sections-pattern)
                            "\\1=\"/__HUGO__/\\2/"
                            result))
              ;; Prefix all other absolute paths with /~saleh
              (setq result (replace-regexp-in-string
                            "\\(href\\|src\\)=\"/\\([^/~_\"]\\)"
                            "\\1=\"/~saleh/\\2"
                            result))
              ;; Restore Hugo URLs
              (setq result (replace-regexp-in-string
                            "/__HUGO__/"
                            "/"
                            result)))
          ;; Fallback if no sections loaded - just prefix everything
          (setq result (replace-regexp-in-string
                        "\\(href\\|src\\)=\"/\\([^/~_\"]\\)"
                        "\\1=\"/~saleh/\\2"
                        result)))
        result)
    output))

(add-to-list 'org-export-filter-final-output-functions #'salih/prefix-absolute-paths)

(defun salih/hugo-id-to-url (id)
  "Return the Hugo URL for the given org ID, or nil if not found."
  (let ((entry (assoc id salih/hugo-id-mapping #'equal)))
    (when entry (cdr entry))))

(defun salih/blog-id-to-url (id)
  "Return the blog URL for the given org ID, or nil if not found."
  (let ((entry (assoc id salih/blog-id-mapping #'equal)))
    (when entry (concat "/~saleh" (cdr entry)))))

(defun salih/is-hugo-node-p (node)
  "Check if NODE is from Hugo content directory."
  (when node
    (let ((file (org-roam-node-file node)))
      (and file (string-match-p "/roam/hugo/content/" file)))))

(defun salih/is-hugo-short-post-p (node)
  "Check if NODE is a Hugo diary or microblog post (treated as short post)."
  (when node
    (let ((file (org-roam-node-file node)))
      (and file
           (string-match-p "/roam/hugo/content/" file)
           (or (string-match-p "/diary/" file)
               (string-match-p "/microblog/" file))))))

;; Override org-id link export to use Hugo URLs
(defun salih/org-id-export-handler (link description format info)
  "Export handler for id: links that resolves Hugo and blog IDs to proper URLs."
  (let* ((id link)
         (hugo-url (salih/hugo-id-to-url id))
         (blog-url (unless hugo-url (salih/blog-id-to-url id)))
         (desc (or description id)))
    (when (eq format 'html)
      (cond
       (hugo-url (format "<a href=\"%s\">%s</a>" hugo-url desc))
       (blog-url (format "<a href=\"%s\">%s</a>" blog-url desc))
       ;; Not found in either mapping, let org handle it normally
       (t nil)))))

;; Add our handler to org-link-parameters for id links
(with-eval-after-load 'ol
  (org-link-set-parameters "id"
                           :export #'salih/org-id-export-handler))

(defun salih/resolve-hugo-id-links (output backend info)
  "Resolve any remaining id: links or file-based Hugo links to proper URLs."
  (if (org-export-derived-backend-p backend 'html)
      (let ((result output))
        ;; First pass: match file-based URLs with ID anchors
        ;; Pattern: href="...hugo/content/.../file.html#ID" or href="...hugo/content/.../file.org#ID"
        (dolist (pair salih/hugo-id-mapping)
          (let* ((id (car pair))
                 (url (cdr pair)))
            ;; Match .html#ID variant
            (setq result (replace-regexp-in-string
                          (format "href=\"[^\"]*hugo/content/[^\"]*/[^\"]*\\.html#%s\"" (regexp-quote id))
                          (format "href=\"%s\"" url)
                          result t t))
            ;; Match .org#ID variant
            (setq result (replace-regexp-in-string
                          (format "href=\"[^\"]*hugo/content/[^\"]*/[^\"]*\\.org#%s\"" (regexp-quote id))
                          (format "href=\"%s\"" url)
                          result t t))
            ;; Match file:// URLs that org might generate
            (setq result (replace-regexp-in-string
                          (format "href=\"file://[^\"]*hugo/content/[^\"]*#%s\"" (regexp-quote id))
                          (format "href=\"%s\"" url)
                          result t t))))
        ;; Second pass: generic pattern for hugo content URLs without ID mapping
        ;; Extract section/filename and create /section/filename/ URL
        (setq result (replace-regexp-in-string
                      "href=\"[^\"]*hugo/content/\\([a-zA-Z-]+\\)/\\([0-9a-zA-Z_-]+\\)\\.\\(org\\|html\\)\\(#[^\"]*\\)?\""
                      "href=\"/\\1/\\2/\""
                      result t nil))
        ;; Third pass: match remaining id: links
        (dolist (pair salih/hugo-id-mapping)
          (let ((id (car pair))
                (url (cdr pair)))
            (setq result (replace-regexp-in-string
                          (format "href=\"id:%s\"" (regexp-quote id))
                          (format "href=\"%s\"" url)
                          result t t))))
        result)
    output))

(add-to-list 'org-export-filter-final-output-functions #'salih/resolve-hugo-id-links)

(defun salih/should-add-backlinks-p ()
  "Check if backlinks should be added to the current buffer.
Returns nil if buffer contains (salih/print-back-links t) or {{{indx}}}."
  (save-excursion
    (goto-char (point-min))
    (not (or (search-forward "(salih/print-back-links t)" nil t)
             (search-forward "(salih/print-back-links)" nil t)
             (search-forward "{{{indx}}}" nil t)))))

(defun salih/format-backlinks-list (blog-nodes private-count)
  "Format the backlinks text with blog references and private note count."
  (let ((blog-count (length blog-nodes)))
    (cond
     ;; Only blog nodes
     ((and (> blog-count 0) (= private-count 0))
      (concat "This section was referenced in "
              (salih/format-node-links blog-nodes)
              "."))
     ((and (= blog-count 0) (> private-count 0))
      nil)
     ((and (> blog-count 0) (> private-count 0))
      (concat "This section was referenced in "
              (salih/format-node-links blog-nodes)
              (format ", and in %d other private note%s."
                      private-count
                      (if (> private-count 1) "s" ""))))
     ;; No backlinks
     (t nil))))

(defun salih/format-node-links (nodes)
  "Format a list of nodes as links with their titles."
  (let* ((links (mapcar (lambda (node)
                          (format "[[id:%s][%s]]"
                                  (org-roam-node-id node)
                                  (org-roam-node-title node)))
                        nodes))
         (link-count (length links)))
    (cond
     ((= link-count 1) (car links))
     ((= link-count 2) (concat (car links) " and " (cadr links)))
     (t (concat (mapconcat 'identity (butlast links) ", ")
                ", and " (car (last links)))))))



(defun salih/get-backlinks-text (id)
  "Get formatted backlinks text for the given ID."
  (when (and id (fboundp 'org-roam-backlinks-get) (salih/should-add-backlinks-p))
    (let* ((node (org-roam-node-from-id id))
           (backlinks (when node (org-roam-backlinks-get node :unique t)))
           (blog-nodes '())
           (private-count 0)
           (skip-titles '("Commentary" "TL;DRs")))
      ;; Classify backlinks, skipping certain titles
      (dolist (backlink backlinks)
        (let* ((source-node (org-roam-backlink-source-node backlink))
               (file-path (org-roam-node-file source-node))
               (title (org-roam-node-title source-node))
               (isexported (not (-contains? (org-roam-node-tags node) "noexport"))))
          (unless (and isexported (member title skip-titles))
            ;; Include both blog content AND Hugo content
            (if (or (cl-search "blog" file-path)
                    (cl-search "/roam/hugo/content/" file-path))
                (push source-node blog-nodes)
              (setq private-count (1+ private-count))))))
      ;; Reverse to maintain order
      (setq blog-nodes (reverse blog-nodes))
      ;; Format the output with wrapper
      (let ((backlinks-text (salih/format-backlinks-list blog-nodes private-count)))
        (when backlinks-text
          (concat "#+BEGIN_BACKLINKS\n" backlinks-text "\n#+END_BACKLINKS"))))))

(defun salih/insert-backlinks-before-export (backend)
  "Insert backlinks text after headings and top-level properties with org:id property.
Inserts BEFORE any #+BEGIN_* blocks or content."
  (when (org-export-derived-backend-p backend 'html)
    (let ((skip-titles '("Commentary" "TL;DRs")))
      (save-excursion
        ;; First, handle top-level document properties (before any headings)
        (goto-char (point-min))
        (let ((first-heading-pos (save-excursion
                                   (re-search-forward org-heading-regexp nil t)))
              (doc-title (or (cadar (org-collect-keywords '("TITLE"))) "")))
          (when (and first-heading-pos
                     (not (member doc-title skip-titles)))
            (goto-char (point-min))
            (when (re-search-forward "^[ \t]*:ID:[ \t]+\\(.+\\)[ \t]*$" first-heading-pos t)
              (let ((id (match-string-no-properties 1)))
                ;; Found an ID in the top-level properties, find insertion point
                (goto-char (point-min))
                (let ((insert-pos (point-min)))
                  ;; Skip past drawers and keyword lines, but stop at #+BEGIN_*
                  (catch 'done
                    (while (< (point) first-heading-pos)
                      (cond
                       ;; Start of a drawer - skip it
                       ((looking-at "^[ \t]*:\\([A-Z]+\\):")
                        (if (re-search-forward "^[ \t]*:END:[ \t]*$" first-heading-pos t)
                            (progn
                              (forward-line 1)
                              (setq insert-pos (point)))
                          (throw 'done nil)))
                       ;; Hit a #+BEGIN_* block - stop here, insert before it
                       ((looking-at "^[ \t]*#\\+BEGIN_")
                        (setq insert-pos (point))
                        (throw 'done nil))
                       ;; Keyword line or empty line - keep going
                       ((or (looking-at "^[ \t]*#\\+")
                            (looking-at "^[ \t]*$"))
                        (forward-line 1)
                        (setq insert-pos (point)))
                       ;; Something else (content) - stop here
                       (t (throw 'done nil)))))
                  ;; Insert backlinks text at the found position
                  (let ((backlinks-text (salih/get-backlinks-text id)))
                    (when backlinks-text
                      (goto-char insert-pos)
                      (insert backlinks-text "\n\n"))))))))

        ;; Now handle all headings with ID property
        (goto-char (point-min))
        (while (re-search-forward org-heading-regexp nil t)
          (let ((element (org-element-at-point)))
            (when (and (eq (org-element-type element) 'headline)
                       (org-element-property :ID element))
              (let ((id (org-element-property :ID element))
                    (title (org-element-property :raw-value element)))
                (unless (member title skip-titles)
                  ;; We're at a headline with an ID
                  (beginning-of-line)
                  (forward-line 1)
                  ;; Skip property drawers, but stop at #+BEGIN_* or content
                  (let ((limit (save-excursion
                                 (or (outline-next-heading)
                                     (point-max))))
                        (insert-pos (point)))
                    (catch 'stop-skip
                      (while (< (point) limit)
                        (cond
                         ;; Drawer - skip it
                         ((looking-at "^[ \t]*:\\([A-Z]+\\):")
                          (let ((drawer-name (match-string 1)))
                            (if (member drawer-name '("PROPERTIES" "DATE" "LOGBOOK" "STATISTICS"))
                                (if (re-search-forward "^[ \t]*:END:[ \t]*$" limit t)
                                    (progn
                                      (forward-line 1)
                                      (setq insert-pos (point)))
                                  ;; Couldn't find END, stop here
                                  (throw 'stop-skip nil))
                              ;; Not a drawer we skip, stop here
                              (throw 'stop-skip nil))))
                         ;; Hit a #+BEGIN_* block - stop here, insert before it
                         ((looking-at "^[ \t]*#\\+BEGIN_")
                          (setq insert-pos (point))
                          (throw 'stop-skip nil))
                         ;; Empty line - keep going
                         ((looking-at "^[ \t]*$")
                          (forward-line 1)
                          (setq insert-pos (point)))
                         ;; Something else (content) - stop here
                         (t (throw 'stop-skip nil)))))
                    ;; Insert backlinks text
                    (let ((backlinks-text (salih/get-backlinks-text id)))
                      (when backlinks-text
                        (goto-char insert-pos)
                        (insert backlinks-text "\n\n")))))))))))))
(add-hook 'org-export-before-processing-functions #'salih/insert-backlinks-before-export)


(defun salih/recents (d)
  (if d
      (s-replace-all '(("class=\"outline" . "class=\"recents")
                       ("<h2 id=\"posts\">Posts</h2>" .
                        "<h2> <a href=\"stack.html\">Top of My Stack</a> </h2> "))
                     (salih/org-string-to-html
                      (salih/org-get-subtree-as-org-string
                       "~/blog/content/stack.org" "Posts")))
    (s-replace-all '(("class=\"outline" . "class=\"footrecents")
                     ("<h2 id=\"posts\">Posts</h2>" .
                      "<h2> <a href=\"stack.html\">Top of My Stack</a> </h2>"))
                   (salih/org-string-to-html)
                   (salih/org-get-subtree-as-org-string
                    "~/blog/content/stack.org" "Posts"))))


(advice-add 'org-html-stable-ids--get-reference :override
            (lambda (orig-fun datum info)
              (if org-html-stable-ids
                  (let ((cache (plist-get info :internal-references))
                        (id (org-html-stable-ids--extract-id datum))
                        (RID (org-element-property :ID datum)))
                    (if (org-roam-node-from-id RID) RID
                      (or (car (rassq datum cache))
                          (progn (while (assoc id cache)
                                   (setq id (org-html--update-string-with-underscore id)))
                                 (when id (push (cons id datum)
                                                cache)
                                       (plist-put info :internal-references cache)
                                       id)))))

                (funcall orig-fun datum info))))


(setq header (with-temp-buffer
               (insert-file-contents "assets/head.html")
               (buffer-string)))
(setq preamble (with-temp-buffer
                 (insert-file-contents "assets/preamble.html")
                 (buffer-string)))

(setq postamalbe (with-temp-buffer
                   (insert-file-contents "assets/postamable.html")
                   (buffer-string)))

(setq org-export-time-stamp-file nil)
(setq org-id-locations-file "~/roam/.orgids")
(defvar salih/org-export-replace-links-counter 0)

(setq org-html-mathjax-options '((path "https://fastly.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js")
                                 (scale 1.0)
                                 (align "center")
                                 (font "mathjax-modern")
                                 (overflow "overflow")
                                 (tags "ams")
                                 (indent "0em")
                                 (multlinewidth "85%")
                                 (tagindent ".8em")
                                 (tagside "right")))

(defun salih/org-string-to-html (org-string)
  "Export an Org-mode string to HTML with proper heading levels and link resolution."
  (let* ((org-export-with-toc nil)
         (org-export-with-section-numbers nil)
         (top-level
          (if (string-match "^\\(\\*+\\)\\s-+" org-string)
              (length (match-string 1 org-string))
            1)))
    (let ((org-html-toplevel-hlevel top-level))
      (with-temp-buffer
        (insert org-string)
        (let ((html (org-export-string-as (buffer-string) 'html t)))
          ;; Apply our link resolution first, then prefix
          (salih/prefix-absolute-paths
           (salih/resolve-hugo-id-links html 'html nil)
           'html nil))))))





(defun salih/get-date (file &optional node)
  (if node
      (cdr (org-id-decode node))
    (let ((date (org-publish-find-property file :date nil)))
      ;; DATE is a secondary string.  If it contains
      ;; a time-stamp, convert it to internal format.
      ;; Otherwise, use FILE modification time.
      (cond ((let ((ts (and (consp date) (assq 'timestamp date))))
               (and ts
                    (let ((value (org-element-interpret-data ts)))
                      (and (org-string-nw-p value)
                           (org-time-string-to-time value))))))
            ((file-exists-p file)
             (file-attribute-modification-time (file-attributes file)))))))

(defun salih/time-less-p (v1 v2 &optional reversed)
  (if reversed
      (time-less-p  timestamp1 timestamp2)
    (time-less-p  timestamp2 timestamp1)))


(defun salih/compare-timestamps (node1 node2)
  "Comparison function to sort structs based on timestamp slot."
  (let* ((node-1-file (org-roam-node-file node1))
         (node-2-file (org-roam-node-file node2))
         (use-id-1 (or
                    (cl-search "/sh/" node-1-file)
                    (cl-search "stack.org" node-1-file)))
         (use-id-2 (or
                    (cl-search "/sh/" node-2-file)
                    (cl-search "stack.org" node-2-file)))
         (timestamp1 (salih/get-date node-1-file (when use-id-1 (org-roam-node-id node1))))
         (timestamp2 (salih/get-date node-2-file (when use-id-2 (org-roam-node-id node2)))))
    (time-less-p  timestamp2 timestamp1)))
;; (cond ((and use-id-1 (not use-id-2)) t)
;;       ((and use-id-2 (not use-id-1)) nil)
;;       ((and (not use-id-1) (not use-id-2)) (time-less-p  timestamp2 timestamp1))
;;       (t (time-less-p  timestamp2 timestamp1)))





(defun salih/get-back-nodes (id &optional no-sort with-sh)
  (let ((backlinks (org-roam-backlinks-get (org-roam-node-from-id id) :unique t))
        nodes '())
    (while backlinks
      (let* ((source-node (org-roam-backlink-source-node (car backlinks)))
             (file (org-roam-node-file source-node))
             ;; Short posts: /sh/, stack.org, OR Hugo diary/microblog
             (shp (or
                   (cl-search "/sh/" file)
                   (cl-search "stack.org" file)
                   (and (cl-search "/roam/hugo/content/" file)
                        (or (cl-search "/diary/" file)
                            (cl-search "/microblog/" file))))))
        (if (or (and with-sh shp) (and (not with-sh) (not shp)))
            (push source-node nodes)))
      (setq backlinks  (cdr backlinks)))
    (if no-sort (reverse (sort nodes #'salih/compare-timestamps))
      (sort nodes #'salih/compare-timestamps))))



(defun salih/mkentity (node counter tag &optional astr)
  (unless astr
    (setq astr "**"))
  (let* ((id (org-roam-node-id node))
         (entry (org-roam-node-file (org-roam-node-from-id id)))
         (lang (if node (salih/get-node-property node "LANG")))
         (subtitle (if lang (salih/get-node-property node "SUBTITLE")))
         (use-id (or
                  (cl-search "/sh/" entry)
                  (cl-search "stack.org" entry)))
         (isexported (not (-contains? (org-roam-node-tags node) "noexport")))
         (is-blog (and isexported (cl-search "blog" (org-roam-node-file node))))
         (is-hugo (and isexported (cl-search "/roam/hugo/content/" (org-roam-node-file node))))
         (preview nil))
    ;; Include both blog content AND Hugo content
    (if (and (or is-blog is-hugo) (not (cl-search "/t/" (org-roam-node-file node))))
        (if tag
            (format "%s %s[[id:%s][%s]]\n#+BEGIN_smth\n%s\n#+END_smth\n"
                    astr
                    (if lang
                        "*Arabic* "
                      "")
                    id
                    (if subtitle
                        subtitle
                      (org-roam-node-title node))
                    (format-time-string "%a %d %b %Y" (salih/get-date entry (when use-id id))))

          (format "%s %s. %s [[id:%s][%s]]\n#+BEGIN_smth\n%s\n#+END_smth\n"
                  astr
                  counter
                  (if lang
                      "*Arabic* "
                    "")
                  id
                  (if subtitle
                      subtitle
                    (org-roam-node-title node))
                  (format-time-string "%a %d %b %Y" (salih/get-date entry (when use-id id)))))

      "")))




(defun salih/compare-org-id (node1 node2)
  (let ((timestamp1 (cdr (org-id-decode  (org-roam-node-id node1))))
        (timestamp2 (cdr (org-id-decode  (org-roam-node-id node2)))))
    (time-less-p  timestamp1 timestamp2)))

(defun salih/print-text-nodes (&optional first)
  (let* ((nodes (sort (salih/get-back-nodes (if first
                                                (org-roam-node-id
                                                 (org-roam-node-from-title-or-alias
                                                  "Commentary"))
                                              (org-entry-get nil "ID" t)))
                      #'salih/compare-org-id))
         (strings '()))
    (if first
        (push (salih/mkinclude (car (last nodes)) nil) strings)
      (while nodes (push (salih/mkinclude (car nodes) nil)
                         strings)
             (setq nodes (cdr nodes))))
    (mapconcat 'identity strings "")))

(defun salih/print-text-nodes-anth ()
  (let* ((nodes (sort (salih/get-back-nodes "3xedczc0i2k0")
                      #'salih/compare-org-id))
         (strings '()))
    (while nodes (push (salih/mkinclude (car nodes) t)
                       strings)
           (setq nodes (cdr nodes)))
    (mapconcat 'identity strings "")))


(defun salih/mkinclude (node remove-title &optional astr)
  (unless astr
    (setq astr "**"))
  (let* ((id (org-roam-node-id node))
         (entry (org-roam-node-file (org-roam-node-from-id id)))
         (cite (file-name-sans-extension (file-name-nondirectory entry))))
    (if remove-title
        (format "#+INCLUDE: \"%s::#%s\" :only-contents t\n\n\n \n/Derived from/ [cite:@%s], no. %s. Appeared: %s\n-----\n"
                entry
                id
                cite
                (substring (cl-first (s-split " " (salih/get-node-property node "NOTER_PAGE"))) 1)
                (format-time-string "%Y-%m-%d (%H:%M)" (cdr (org-id-decode  (org-roam-node-id node)))))

      (format "#+INCLUDE: \"%s::#%s\" :only-contents nil\n"
              entry
              id))))


(defun salih/get-node-property (node property)
  (cdr (assoc property (org-roam-node-properties node))))



(defun salih/org-get-subtree-as-org-string (file-path heading)
  "Get the content of the subtree under a given HEADING in the Org file at FILE-PATH as an Org string."
  (with-temp-buffer
    ;; Load the Org file
    (insert-file-contents file-path)
    (org-mode)
    (goto-char (point-min))
    ;; Search for the specified heading
    (if (re-search-forward (concat "^\\*+ " (regexp-quote heading)) nil t)
        (let ((start (line-beginning-position))
              (end (progn
                     ;; Move to the next heading at the same level or higher
                     (org-end-of-subtree t t)
                     (point))))
          ;; Return the substring between start and end
          (buffer-substring-no-properties start end))
      (error "Heading '%s' not found in %s" heading file-path))))




(defun salih/length (l)
  (let ((counter 0))
    (while l
      (when (and (car l)
                 (let ((file (org-roam-node-file (car l))))
                   (or (cl-search "blog" file)
                       (cl-search "/roam/hugo/content/" file))))
        (setq counter (+ counter 1)))
      (setq l (cdr l)))
    counter))



(defun salih/include-recents ()
  (salih/org-string-to-html (org-export-expand-include-keyword)))



(defun salih/get-backlinks-html (&optional tag sh astr)
  (let* ((nodes (salih/get-back-nodes (org-entry-get nil "ID" t) tag sh))
         (strings '())
         (counter (salih/length nodes)))
    (while nodes (push (salih/org-string-to-html (salih/mkentity
                                                  (car nodes)
                                                  counter tag astr))
                       strings)
           (if (and (car nodes)
                    (let ((file (org-roam-node-file (car nodes))))
                      (or (cl-search "blog" file)
                          (cl-search "/roam/hugo/content/" file))))
               (setq counter (- counter 1)))
           (setq nodes (cdr nodes)))


    (mapconcat 'identity strings "")))

(defun salih/print-back-links (&optional tag treat-shorts-as-long)
  (concat (salih/get-backlinks-html tag nil) "\n"
          (let ((shorts
                 (salih/get-backlinks-html t t (if treat-shorts-as-long nil "***"))))
            (unless (and (equal shorts ""))
              (concat (unless treat-shorts-as-long
                        (salih/org-string-to-html "** Short Posts")) "\n" shorts)))))



(defun salih/get-preview (file)
  (if t
      nil
    (with-temp-buffer
      (insert-file-contents file)
      (goto-char (point-min))
      (when (re-search-forward "^#\\+BEGIN_PREVIEW$" nil 1)
        (goto-char (point-min))
        (let ((beg (+ 1 (re-search-forward "^#\\+BEGIN_PREVIEW$" nil 1)))
              (end (progn (re-search-forward "^#\\+END_PREVIEW$" nil 1)
                          (match-beginning 0))))
          (goto-char beg)
          (while (search-forward "\n" end t)
            (replace-match " " nil t))
          (buffer-substring beg end))))))

(defun salih/delete-index (list)
  "Delete items containing the word 'index' from LIST."
  (cond
   ((null list) nil)
   ((atom list)
    (if (stringp list)
        (unless (string-match-p "index.org" list)
          list)
      list))
   (t
    (let ((car-result (salih/delete-index (car list)))
          (cdr-result (salih/delete-index (cdr list))))
      (if (and (null car-result) (null cdr-result))
          nil
        (cons car-result cdr-result))))))


(defun salih/org-publish-org-sitemap (title list)
  "Sitemap generation function."
  (concat "#+OPTIONS: toc:nil")
  (org-list-to-subtree (salih/delete-index list)))

;; modify this one!
(defun salih/org-publish-org-sitemap-format (entry style project)
  "Custom sitemap entry formatting: add date"
  (cond ((not (directory-name-p entry))
         (let* ((preview nil)
                (title (org-publish-find-title entry project))
                (node (org-roam-node-from-title-or-alias title))
                (lang (if node (salih/get-node-property node "LANG")))
                (subtitle (if lang (salih/get-node-property node "SUBTITLE"))))
           (format "%s[[file:%s][%s]]\n#+BEGIN_smth\n%s\n#+END_smth\n"
                   (if lang
                       "*Arabic* "
                     "")
                   entry
                   (if subtitle
                       subtitle
                     title)
                   (format-time-string "%a %d %b %Y" (org-publish-find-date entry
                                                                            project)))))

        ((eq style 'tree)
         (file-name-nondirectory (directory-file-name entry)))
        (t entry)))

(defun salih/file-contents (file)
  (with-temp-buffer
    (insert-file-contents file)
    (buffer-string)))


;;; additional settings
(setq org-html-style-default (salih/file-contents "assets/head.html"))


(setq org-html-prefer-user-labels t)

(setq org-export-with-clocks t)


(setq org-export-with-clocks t)

(defun org-html-timestamp (timestamp _contents info)
  "Transcode a TIMESTAMP object from Org to HTML.
CONTENTS is nil.  INFO is a plist holding contextual
information."
  (let* ((ts (org-timestamp-translate timestamp))
         (time (apply #'encode-time (org-parse-time-string ts)))
         (formatted-time (format-time-string "[%Y-%m-%d %a %H:%M]" time)))
    (format "<span class=\"timestamp-wrapper\"><span class=\"timestamp\">%s</span></span>"
            (replace-regexp-in-string "--" "&#x2013;" formatted-time))))


;; (defun org-drawerkk (name content)
;;   (format "@<div class=\"notes\"> %s @</div>" content))

;; (setq org-html-format-drawer-function 'org-drawerkk)
(setq org-time-stamp-custom-formats '("<%a %b %e %Y>" . "<%a %b %e %Y %H:%M>"))

(defun org-drawerkk (name content)
  (if (s-equals? name "REVIEW_DATA")
      ""
    (format "<div class=\"notes\"> %s </div>" content)))


(setq org-html-format-drawer-function 'org-drawerkk)



(defun salih/org-html-publish-to-tufte-html (plist filename pub-dir)
  "Make sure that the file is not already published befeore really publihing
it."
  ;; rebuilding all for now
  (let* ((rebuild t)
         (html (let* ((org-inhibit-startup t)
                      (visiting (find-buffer-visiting filename))
                      (salih/rebuild nil)
                      (extension (concat "." (or (plist-get plist :html-extension)
                                                 org-html-extension
                                                 "html")))
                      (work-buffer (or visiting (find-file-noselect filename))))
                 (unwind-protect
                     (with-current-buffer work-buffer
                       (when (ignore-errors (buffer-local-value 'salih/rebuild work-buffer))
                         (setq rebuild t))
                       (progn
                         (org-export-output-file-name extension nil pub-dir)))))))
    (when (or (string-match ".*index.*" filename)
              rebuild (file-newer-than-file-p filename html))
      (org-html-publish-to-tufte-html plist filename pub-dir))))



(setq my/org-referenced-filenames
      (let* ((org-dir (expand-file-name "content/" "~/blog"))
             (all-org (directory-files-recursively org-dir "\\.org\\'"))
             (filenames '()))
        (dolist (f all-org)
          (with-temp-buffer
            ;; locally pretend tabs are 8 columns
            (setq-local tab-width 8)
            (insert-file-contents f)
            (org-element-map (org-element-parse-buffer) 'link
              (lambda (lnk)
                (when (string= (org-element-property :type lnk) "file")
                  (push (file-name-nondirectory
                         (org-element-property :path lnk))
                        filenames))))))
        (delete-dups filenames)))


(defun salih/org-publish-attachment-if-referenced (plist filename pub-dir)
  "Publish the file at FILENAME into PUB-DIR only if its basename is in `my/org-referenced-filenames`."
  (let* ((basename (file-name-nondirectory filename)))
    (if (member basename my/org-referenced-filenames)
        (progn
          (unless (file-directory-p pub-dir)
            (make-directory pub-dir t))
          (let ((dest (expand-file-name basename pub-dir)))
            (unless (file-equal-p (file-truename filename)
                                  (file-truename dest))
              (copy-file filename dest t)) dest))
      (message basename "is not in my list"))))





(defun salih/set-org-publish-project-alist ()
  "Set publishing projects for Orgweb and Worg."
  (interactive)
  (setq org-publish-project-alist
        `(("blog-notes"
           ;; Directory for source files in org format
           :language "en"
           :base-directory "./content"
           :base-extension "org"
           :html-doctype "html5"
           :html-head ,header
           :html-html5-fancy t
           ;; HTML directory
           :publishing-directory "/Users/l/roam/hugo/static/~saleh"
           :recursive t
           :headline-levels 8
           :with-sub-superscript nil
           :section-numbers nil
           :auto-preamble nil
           :html-preamble ,preamble
           :html-postamble ,postamalbe

           :with-drawers t
           :auto-sitemap t
           :sitemap-title nil
           :sitemap-format-entry salih/org-publish-org-sitemap-format
           :sitemap-function salih/org-publish-org-sitemap
           :sitemap-sort-files anti-chronologically
           :sitemap-filename "sitemap.org"
           :sitemap-style tree
           :with-toc nil

           :publishing-function salih/org-html-publish-to-tufte-html
           :exclude "\!.*\.org"
           :makeindex t
           :html-head-include-default-style nil)

          ("blog-static"
           :base-directory "./content"
           :base-extension "css\\|js\\|png\\|jpg\\|html\\|json\\|jpeg\\|gif\\|svg\\|pdf\\|mp3\\|woff2\\|woff"
           :publishing-directory "/Users/l/roam/hugo/static/~saleh"
           :recursive t
           :publishing-function org-publish-attachment)

          ;; ("media"
          ;;  :base-directory "../media"
          ;;  :base-extension   "mp4\\|png\\|jpe?g\\|gif\\|svg"
          ;;  :publishing-directory "public/media"
          ;;  :recursive t
          ;;  :publishing-function salih/org-publish-attachment-if-referenced)

          ("assets"
           :base-directory "./assets"
           :base-extension "css\\|js\\|png\\|jpg\\|gif\\|svg\\|pdf\\|mp3\\|woff2\\|woff\\|html\\|md\\|ico"
           :publishing-directory "/Users/l/roam/hugo/static/~saleh"
           :recursive t
           :publishing-function org-publish-attachment)

          ("blog" :components ("blog-notes"
                               ;; "media"
                               "assets" "blog-static")))))




(salih/set-org-publish-project-alist)


(add-hook! 'org-mode-hook (projectile-mode -1))
(org-publish-all t)
(remove-hook! 'org-mode-hook (projectile-mode -1))

;; Generate ID→URL mapping for Hugo
(defun salih/generate-blog-id-mapping ()
  "Generate a JSON mapping of org IDs to published URLs for Hugo."
  (let ((mapping '())
        (content-dir "/Users/l/blog/content/"))
    ;; Scan all org files in blog content directory
    (dolist (file (directory-files-recursively content-dir "\\.org$"))
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        ;; Find all :ID: properties in the file
        (while (re-search-forward "^[ \t]*:ID:[ \t]+\\(.+\\)[ \t]*$" nil t)
          (let* ((id (match-string-no-properties 1))
                 (rel-path (file-relative-name file content-dir))
                 (html-path (concat "/" (file-name-sans-extension rel-path) ".html")))
            (push (cons id html-path) mapping)))))
    (with-temp-file "/Users/l/roam/hugo/data/blog_ids.json"
      (insert "{\n")
      (let ((first t))
        (dolist (pair mapping)
          (unless first (insert ",\n"))
          (setq first nil)
          (insert (format "  %S: %S" (car pair) (cdr pair)))))
      (insert "\n}\n"))
    (message "Generated blog ID mapping with %d entries" (length mapping))))

(salih/generate-blog-id-mapping)

(with-temp-buffer
  (call-process "python3" nil t nil "/Users/l/roam/hugo/scripts/generate_hugo_ids.py"))

(message "Build Complete!")


(setq org-html-htmlize-output-type 'inline-css) ; Disable syntax highlighting

(setq indent-bars-starting-column 0)
